// <auto-generated />
namespace MyBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class datearticle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datearticle));
        
        string IMigrationMetadata.Id
        {
            get { return "201904291449537_date article"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
